"""Export answers to disk as Markdown or JSON.

Two things worth noting about the design:

* **The caller never supplies a filename.** It is derived server-side from a
  timestamp and the request id, so there is no path traversal surface at all —
  the alternative (sanitising a user-supplied name) is a much easier thing to
  get subtly wrong.
* **Markdown carries the provenance, not just the answer.** An exported answer
  with no citations, groundedness score, or guardrail verdicts is just a claim;
  the point of this system is that every answer is traceable, and the export
  should preserve that rather than flatten it.
"""

from __future__ import annotations

import json
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable

from .config import DATA_DIR

EXPORT_DIR = DATA_DIR / "exports"
_SAFE = re.compile(r"[^a-zA-Z0-9_-]+")


def _slug(text: str, limit: int = 40) -> str:
    """A short, filesystem-safe hint of the question — for humans scanning the
    folder. Never used as the whole filename, so it can be lossy."""
    ascii_ish = _SAFE.sub("-", (text or "").strip())[:limit].strip("-").lower()
    return ascii_ish or "query"


def _fmt_ms(value: Any) -> str:
    try:
        return f"{float(value):.1f} ms"
    except (TypeError, ValueError):
        return "—"


def render_markdown(answers: Iterable[dict], title: str = "Voice RAG export") -> str:
    answers = list(answers)
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    out: list[str] = [
        f"# {title}",
        "",
        f"_{len(answers)} answer{'s' if len(answers) != 1 else ''} · exported {now}_",
        "",
        "Retrieved from **ai4bharat/MSMARCO-XI**. Every answer below records the "
        "passages it was built from, a measured groundedness score, and the "
        "guardrails that ran.",
        "",
        "---",
        "",
    ]

    for i, a in enumerate(answers, 1):
        q = a.get("query") or a.get("transcript") or "(no question)"
        out.append(f"## {i}. {q}")
        out.append("")

        if a.get("transcript") and a.get("transcript") != a.get("query"):
            out.append(f"> Heard as: _{a['transcript']}_")
            out.append("")

        if a.get("answered"):
            out.append(a.get("answer", "").strip() or "_(empty)_")
        else:
            reason = a.get("abstain_reason") or "unspecified"
            out.append(f"**The system declined to answer.** (`{reason}`)")
            out.append("")
            out.append(f"> {a.get('answer', '').strip()}")
        out.append("")

        lat = a.get("latency") or {}
        facts = [
            f"**Mode** `{a.get('mode', '—')}`",
            f"**Core latency** {_fmt_ms(lat.get('core_ms'))}",
        ]
        if lat.get("stt_ms") is not None:
            facts.append(f"**Speech-to-text** {_fmt_ms(lat.get('stt_ms'))}")
        if a.get("answered"):
            facts.append(f"**Groundedness** {float(a.get('groundedness') or 0) * 100:.0f}%")
            facts.append(f"**Confidence** {float(a.get('confidence') or 0):.2f}")
        if a.get("cross_lingual"):
            langs = ", ".join(a.get("evidence_languages") or [])
            facts.append(f"**Cross-lingual** answered from {langs}")
        if a.get("degraded"):
            facts.append(f"**Degraded** `{a.get('degraded_reason')}`")
        out.append(" · ".join(facts))
        out.append("")

        cites = a.get("citations") or []
        if cites:
            out.append("### Evidence")
            out.append("")
            for c in cites:
                out.append(
                    f"- **`{c.get('doc_id')}`** "
                    f"({c.get('strategy')}, {c.get('lang')}, score {float(c.get('score') or 0):.3f})  "
                )
                snippet = (c.get("snippet") or "").replace("\n", " ").strip()
                out.append(f"  > {snippet}")
            out.append("")

        rails = ((a.get("guardrails") or {}).get("results")) or []
        if rails:
            verdicts = ", ".join(
                f"{r.get('name')}: {r.get('verdict')}" for r in rails
            )
            out.append(f"<sub>Guardrails — {verdicts}</sub>")
            out.append("")

        spans = lat.get("spans") or []
        if spans:
            timings = " · ".join(f"{s.get('name')} {_fmt_ms(s.get('duration_ms'))}" for s in spans)
            out.append(f"<sub>Pipeline — {timings}</sub>")
            out.append("")

        out.append("---")
        out.append("")

    out.append(
        "<sub>Generated by Voice RAG · "
        "https://github.com/tilakn21/voice-enabled-rag · #RAGInGoa</sub>"
    )
    return "\n".join(out)


def export_answers(answers: list[dict], fmt: str = "md") -> dict:
    """Write answers to `data/exports/` and describe where they landed."""
    fmt = (fmt or "md").lower()
    if fmt not in {"md", "json"}:
        raise ValueError(f"unsupported export format {fmt!r}; use 'md' or 'json'")
    if not answers:
        raise ValueError("nothing to export")

    EXPORT_DIR.mkdir(parents=True, exist_ok=True)

    stamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    first = answers[0]
    hint = _slug(first.get("query") or first.get("transcript") or "")
    suffix = "session" if len(answers) > 1 else hint
    name = f"{stamp}-{suffix}.{fmt}"
    path = EXPORT_DIR / name

    if fmt == "md":
        body = render_markdown(answers)
    else:
        body = json.dumps(
            {
                "exported_at": datetime.now(timezone.utc).isoformat(),
                "source": "ai4bharat/MSMARCO-XI",
                "n_answers": len(answers),
                "answers": answers,
            },
            ensure_ascii=False,
            indent=2,
        )

    path.write_text(body, encoding="utf-8")
    return {
        "path": str(path),
        "relative_path": str(path.relative_to(DATA_DIR.parent)),
        "filename": name,
        "format": fmt,
        "bytes": len(body.encode("utf-8")),
        "n_answers": len(answers),
        "directory": str(EXPORT_DIR),
    }


def list_exports(limit: int = 50) -> list[dict]:
    if not EXPORT_DIR.exists():
        return []
    files = sorted(EXPORT_DIR.glob("*.*"), key=lambda p: p.stat().st_mtime, reverse=True)
    return [
        {
            "filename": f.name,
            "bytes": f.stat().st_size,
            "modified": datetime.fromtimestamp(f.stat().st_mtime, timezone.utc).isoformat(),
        }
        for f in files[:limit]
    ]
